// raw/<name>.svg (Figma exports) → src/index.tsx (one React component per icon).
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";

const raw = new URL("../raw/", import.meta.url);
const src = new URL("../src/", import.meta.url);

// Figma MCP exports include the surrounding canvas; keep only the icon's own
// variant group (<g id="Size=20…">). REST exports are already just the icon.
function iconBody(svg, name) {
  if (!/^<svg[^>]*width="20" height="20"/.test(svg)) throw new Error(`${name}: expected a 20×20 export`);
  const open = svg.match(/<g id="(?:Size|Property 1|Style)=[^"]*"[^>]*>/);
  if (!open) return svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  let depth = 1;
  let i = open.index + open[0].length;
  const start = i;
  const tag = /<(\/?)g\b[^>]*?(\/?)>/g;
  tag.lastIndex = i;
  for (let m; (m = tag.exec(svg)); ) {
    if (m[2]) continue;
    depth += m[1] ? -1 : 1;
    if (depth === 0) return svg.slice(start, m.index);
    i = tag.lastIndex;
  }
  throw new Error(`${name}: unbalanced <g>`);
}

const toJsx = (body) =>
  body
    .replace(/\s(?:id|clip-path|data-[\w-]+)="[^"]*"/g, "")
    // ponytail: every non-white colour becomes currentColor; white stays as the knockout in filled icons
    .replace(/(fill|stroke)="(?!none|white|#fff(?:fff)?")[^"]*"/gi, '$1="currentColor"')
    .replace(/\s([a-z]+(?:-[a-z]+)+)=/g, (_, a) => " " + a.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + "=")
    .trim();

const pascal = (name) => name.replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase());

const files = (await readdir(raw)).filter((f) => f.endsWith(".svg")).sort();
const components = await Promise.all(
  files.map(async (file) => {
    const name = file.slice(0, -4);
    const body = toJsx(iconBody(await readFile(new URL(file, raw), "utf8"), name));
    return `export const ${pascal(name)}Icon = (props: IconProps) => (\n  <Icon {...props}>\n    ${body.replace(/\n/g, "\n    ")}\n  </Icon>\n);`;
  }),
);

await mkdir(src, { recursive: true });
await writeFile(
  new URL("index.tsx", src),
  `// Generated by scripts/build.mjs from raw/*.svg — do not edit.
import type { SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement> & { size?: number | string };

function Icon({ size = 16, children, ...props }: IconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 20 20"
      fill="none"
      aria-hidden={props["aria-label"] ? undefined : true}
      {...props}
    >
      {children}
    </svg>
  );
}

${components.join("\n\n")}
`,
);
console.log(`Built ${files.length} icons.`);
